[package]
name = "dy_panic"
version = "0.1.0"
authors = ["edwin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
some_dy = {path = "some_dy"}
some_staticlib = {path = "some_staticlib"}

dylib = "0.0.3"
